version: "3.8" # DC version

services:
  web: 
    build: . # build image in current dir
    ports:
      - "5000:5000" # map container port 5000 to local port 5000
    environment: # env variables
      - FLASK_APP=app.py
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=my_db
    depends_on:
      - mysql # start msql service first
    networks:
      - app-network # connect service to custom network
    volumes:
      - ./app:/app #  local 'app' folder into '/app' inside the container

  mysql: 
    image: mysql:8.0 #  official MySQL 8.0 image
    restart: always # restart automatically
    environment: # env variables
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=my_db 
    ports:
      - "3306:3306" # map container port 3306 to local port 3306
    volumes:
      - mysql-data:/var/lib/mysql # persist MysQL data in docker volume
    networks:
      - app-network # connect service to custom network


networks:
  app-network:


volumes:
  mysql-data:
